### DISCUSSION TITLE
Best/easiest way to run multiple instances of the bot

### DISCUSSION THREAD

**Discussion by lozbinks** [jef/streetmerchant#2391] [Help]
Hi guys,

Can anyone advise what's the easiest way to run multiple instances of the bot?

I.e have one instance checking x number of sites for 3060 cards, another checking x number of sites for 3070 cards and so on..

**Comment by ReflexivR** [comment]
What's wrong with just copying the folder and running a new instance from that path? Works fine for me.

**Comment by PlueSwe** [comment]
Do you need to copy everything for each bot?

**Comment by klords** [comment]
If you're not opposed to running in docker, you can set up a simple `docker-compose.yml` file like this:

```
version: '3.0'
services:
  streetmerchant-3070:
    image: ghcr.io/jef/streetmerchant:nightly
    container_name: streetmerchant-3070
    restart: always
    env_file:
      - 3070-dotenv
    logging:
      driver: 'local'
  streetmerchant-3060ti:
    image: ghcr.io/jef/streetmerchant:nightly
    container_name: streetmerchant-3060ti
    restart: always
    env_file:
      - 3060ti-dotenv
    logging:
      driver: 'local'
```

Make sure the dotenv file you want to use for each instance is in the same directory as this file, and then you can simply run them all together with `docker-compose up -d` and stop them with `docker-compose down`
