### ISSUE TITLE
StreetMerchant stuck at process start

### ISSUE THREAD

**Issue by AlphaOmega2020** [jef/streetmerchant#1111]
### Description

SM gets "stuck" here any doesn't progress:
```
Recreating streetmerchant ... done
Attaching to streetmerchant
streetmerchant    |
streetmerchant    | > streetmerchant@ start:production /app
streetmerchant    | > node build/index.js
streetmerchant    |
streetmerchant    | ＳＴＲＥＥＴＭＥＲＣＨＡＮＴ
streetmerchant    | 3.1.0
streetmerchant    |

```

If i run with the default "blank" example .env, i get a TWILIO error about account needing to start with AC... if i remove the TWILIO lines from the .env and leave everything else as default i get the same issue whereby its stuck as per above.

compose:
```
    streetmerchant:
        container_name: streetmerchant
        environment:
            - 'PUID=1000'
            - 'PGID=100'
            - 'TZ=Europe/London'
            - 'PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser'
            - 'PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1'
            - 'DOCKER=true'
        cap_add:
            - 'SYS_ADMIN'
        env_file:
            - '/share/Container/container-station-data/appdata/streetmerchant/config/.env'
        network_mode: default
#        volumes:
#            - '/share/Container/container-station-data/appdata/streetmerchant/config/.env:/.env'
        restart: unless-stopped
        image: ghcr.io/jef/streetmerchant:latest
```

.env - version 1

```
# ** All configuration variables are optional **
# Read https://github.com/jef/streetmerchant#customization for help on customizing this file
#############################################################################################

ASCII_BANNER=""
ASCII_COLOR=""
AUTO_ADD_TO_CART=""
BROWSER_TRUSTED=""
COUNTRY="UK"
DESKTOP_NOTIFICATIONS=""
DISCORD_NOTIFY_GROUP=""
DISCORD_WEB_HOOK="https://discordapp.com/api/webhooks/779845508180869138/wtyglv-LjAI21cgnixC-j9y-jjUwKoBwsEjl8b72RmNVgZ_fHEUCd_QjVdaINWhVUc0x"
EMAIL_PASSWORD=""
EMAIL_TO=""
EMAIL_USERNAME=""
HEADLESS="true"
IN_STOCK_WAIT_TIME="1"
LOG_LEVEL="debug"
LOW_BANDWIDTH=""
MAX_PRICE_SERIES_3060TI="1"
MAX_PRICE_SERIES_3070="1"
MAX_PRICE_SERIES_3080="1"
MAX_PRICE_SERIES_3090="1000"
MAX_PRICE_SERIES_CORSAIR_SF="1"
AX_PRICE_SERIES_RX6800="1"
MAX_PRICE_SERIES_RX6800XT="650"
MAX_PRICE_SERIES_RX6900XT="800"
MAX_PRICE_SERIES_RYZEN5600="1"
MAX_PRICE_SERIES_RYZEN5800="1"
MAX_PRICE_SERIES_RYZEN5900="1"
MAX_PRICE_SERIES_RYZEN5950="751"
MAX_PRICE_SERIES_SONYPS5C="400"
MAX_PRICE_SERIES_SONYPS5DE="200"
MAX_PRICE_SERIES_TEST=""
MICROCENTER_LOCATION=""
MQTT_BROKER_ADDRESS=""
MQTT_BROKER_PORT=""
MQTT_CLIENT_ID=""
MQTT_PASSWORD=""
MQTT_QOS=""
MQTT_TOPIC=""
MQTT_USERNAME=""
NVIDIA_ADD_TO_CART_ATTEMPTS=""
NVIDIA_SESSION_TTL=""
OPEN_BROWSER=""
PAGE_BACKOFF_MIN=""
PAGE_BACKOFF_MAX=""
PAGE_SLEEP_MIN=""
PAGE_SLEEP_MAX=""
PAGE_TIMEOUT=""
PAGERDUTY_INTEGRATION_KEY=""
PAGERDUTY_SEVERITY=""
PHILIPS_HUE_API_KEY=""
PHILIPS_HUE_CLOUD_ACCESS_TOKEN=""
PHILIPS_HUE_CLOUD_CLIENT_ID=""
PHILIPS_HUE_CLOUD_CLIENT_SECRET=""
PHILIPS_HUE_CLOUD_REFRESH_TOKEN=""
PHILIPS_HUE_LAN_BRIDGE_IP=""
PHILIPS_HUE_LIGHT_COLOR=""
PHILIPS_HUE_LIGHT_IDS=""
PHILIPS_HUE_LIGHT_PATTERN=""
PHONE_CARRIER=""
PHONE_NUMBER=""
PLAY_SOUND=""
PROXY_ADDRESS=""
PROXY_PROTOCOL=""
PROXY_PORT=""
PUSHBULLET=""
PUSHOVER_TOKEN=""
PUSHOVER_USER=""
PUSHOVER_PRIORITY=""
SCREENSHOT=""
SHOW_ONLY_BRANDS=""
SHOW_ONLY_MODELS=""
SHOW_ONLY_SERIES=""
SLACK_CHANNEL=""
SLACK_TOKEN=""
SMTP_ADDRESS=""
SMTP_PORT=""
STORES="scan, amazon-uk, amd, box, currys, game, novatech, overclockers, very"
TELEGRAM_ACCESS_TOKEN=""
TELEGRAM_CHAT_ID=""
TWITCH_ACCESS_TOKEN=""
TWITCH_CHANNEL=""
TWITCH_CLIENT_ID=""
TWITCH_CLIENT_SECRET=""
TWITCH_REFRESH_TOKEN=""
TWITTER_ACCESS_TOKEN_KEY=""
TWITTER_ACCESS_TOKEN_SECRET=""
TWITTER_CONSUMER_KEY=""
TWITTER_CONSUMER_SECRET=""
TWITTER_TWEET_TAGS=""
USER_AGENT=""
WEB_PORT=""
PUPPETEER_EXECUTABLE_PATH="/usr/bin/chromium-browser"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD="1"
DOCKER="true"
PUID="1000"
PGID="100"
TZ="Europe/London"
```

.env - version 2

```
# ** All configuration variables are optional **
# Read https://github.com/jef/streetmerchant#customization for help on customizing this file
#############################################################################################

ASCII_BANNER=""
ASCII_COLOR=""
AUTO_ADD_TO_CART=""
BROWSER_TRUSTED=""
COUNTRY="UK"
DESKTOP_NOTIFICATIONS=""
DISCORD_NOTIFY_GROUP=""
DISCORD_WEB_HOOK="https://discordapp.com/api/webhooks/779845508180869138/wtyglv-LjAI21cgnixC-j9y-jjUwKoBwsEjl8b72RmNVgZ_fHEUCd_QjVdaINWhVUc0x"
EMAIL_PASSWORD=""
EMAIL_TO=""
EMAIL_USERNAME=""
HEADLESS="true"
IN_STOCK_WAIT_TIME="1"
LOG_LEVEL="debug"
LOW_BANDWIDTH=""
MAX_PRICE_SERIES_3060TI="1"
MAX_PRICE_SERIES_3070="1"
MAX_PRICE_SERIES_3080="1"
MAX_PRICE_SERIES_3090="1000"
MAX_PRICE_SERIES_CORSAIR_SF="1"
AX_PRICE_SERIES_RX6800="1"
MAX_PRICE_SERIES_RX6800XT="650"
MAX_PRICE_SERIES_RX6900XT="800"
MAX_PRICE_SERIES_RYZEN5600="1"
MAX_PRICE_SERIES_RYZEN5800="1"
MAX_PRICE_SERIES_RYZEN5900="1"
MAX_PRICE_SERIES_RYZEN5950="751"
MAX_PRICE_SERIES_SONYPS5C="400"
MAX_PRICE_SERIES_SONYPS5DE="200"
MAX_PRICE_SERIES_TEST=""
MICROCENTER_LOCATION=""
MQTT_BROKER_ADDRESS=""
MQTT_BROKER_PORT=""
MQTT_CLIENT_ID=""
MQTT_PASSWORD=""
MQTT_QOS=""
MQTT_TOPIC=""
MQTT_USERNAME=""
NVIDIA_ADD_TO_CART_ATTEMPTS=""
NVIDIA_SESSION_TTL=""
OPEN_BROWSER=""
PAGE_BACKOFF_MIN=""
PAGE_BACKOFF_MAX=""
PAGE_SLEEP_MIN=""
PAGE_SLEEP_MAX=""
PAGE_TIMEOUT=""
PAGERDUTY_INTEGRATION_KEY=""
PAGERDUTY_SEVERITY=""
PHILIPS_HUE_API_KEY=""
PHILIPS_HUE_CLOUD_ACCESS_TOKEN=""
PHILIPS_HUE_CLOUD_CLIENT_ID=""
PHILIPS_HUE_CLOUD_CLIENT_SECRET=""
PHILIPS_HUE_CLOUD_REFRESH_TOKEN=""
PHILIPS_HUE_LAN_BRIDGE_IP=""
PHILIPS_HUE_LIGHT_COLOR=""
PHILIPS_HUE_LIGHT_IDS=""
PHILIPS_HUE_LIGHT_PATTERN=""
PHONE_CARRIER=""
PHONE_NUMBER=""
PLAY_SOUND=""
PROXY_ADDRESS=""
PROXY_PROTOCOL=""
PROXY_PORT=""
PUSHBULLET=""
PUSHOVER_TOKEN=""
PUSHOVER_USER=""
PUSHOVER_PRIORITY=""
SCREENSHOT=""
SHOW_ONLY_BRANDS=""
SHOW_ONLY_MODELS=""
SHOW_ONLY_SERIES=""
SLACK_CHANNEL=""
SLACK_TOKEN=""
SMTP_ADDRESS=""
SMTP_PORT=""
STORES="scan, amazon-uk, amd, box, currys, game, novatech, overclockers, very"
TELEGRAM_ACCESS_TOKEN=""
TELEGRAM_CHAT_ID=""
TWITCH_ACCESS_TOKEN=""
TWITCH_CHANNEL=""
TWITCH_CLIENT_ID=""
TWITCH_CLIENT_SECRET=""
TWITCH_REFRESH_TOKEN=""
TWITTER_ACCESS_TOKEN_KEY=""
TWITTER_ACCESS_TOKEN_SECRET=""
TWITTER_CONSUMER_KEY=""
TWITTER_CONSUMER_SECRET=""
TWITTER_TWEET_TAGS=""
USER_AGENT=""
WEB_PORT=""
```

Docker Version
```
[~] # docker version
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   0bbe3ac
 Built:        Wed Nov 27 03:52:27 2019
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   0bbe3ac
 Built:        Wed Nov 27 03:52:27 2019
 OS/Arch:      linux/amd64
 Experimental: false
```
